version: '3'

services:
  app:
    image: hseeberger/scala-sbt:8u151-2.12.4-1.0.2
    ports:
      - "6060:6060"
    working_dir: /app
    volumes:
      - .:/app
      - ~/.ivy2:/root/.ivy2
      - ~/.sbt:/root/.sbt
    command: sbt run